### ISSUE TITLE
作者还在吗

### ISSUE THREAD

**Issue by deutdrsium** [TheresaQAQ/Ding-Talk-Auto#3]
Traceback (most recent call last):
  File "D:\.DingTalk\Ding-Talk-Auto-master\DingTalkAuto.py", line 172, in <module>
    main()
  File "D:\.DingTalk\Ding-Talk-Auto-master\DingTalkAuto.py", line 92, in main
    if pyautogui.locateOnScreen(path_InDT) != None:
  File "E:\python3.9\lib\site-packages\pyautogui\__init__.py", line 175, in wrapper
    return wrappedFunction(*args, **kwargs)
  File "E:\python3.9\lib\site-packages\pyautogui\__init__.py", line 213, in locateOnScreen
    return pyscreeze.locateOnScreen(*args, **kwargs)
  File "E:\python3.9\lib\site-packages\pyscreeze\__init__.py", line 371, in locateOnScreen
    screenshotIm = screenshot(region=None) # the locateAll() function must handle cropping to return accurate coordinates, so don't pass a region here.
  File "E:\python3.9\lib\site-packages\pyscreeze\__init__.py", line 143, in wrapper
    raise PyScreezeException('The Pillow package is required to use this function.')
pyscreeze.PyScreezeException: The Pillow package is required to use this function.

**Comment by deutdrsium** [comment]
其实可以整个后台抓包什么的（我也不太懂
不然总跳出来还是有点打扰的
